services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile_nginx
    ports:
      - "80:80"
    volumes:
      - ./app/:/usr/share/nginx/html/
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: dockerfile_php
    expose:
      - "9000"
    volumes:
      - ./app:/var/www/html
