- name: Instalar utilidades base
  hosts: dev-servers
  become: yes
  tasks:
    - name: Instalar herramientas útiles
      apt:
        name:
          - htop
          - git
          - curl
          - wget
          - unzip
        state: present
        update_cache: yes