---
- name: Listamos componentes de k8s
  hosts: dev-servers
  become: yes

  tasks:
    - name: Listar componentes de k8s
      shell: "/snap/bin/microk8s kubectl get all"
      register: listar
      
    - name: Mostrar salida de listado
      debug:
        var: listar.stdout_lines