---
- name: Rollback del deployment a la versión anterior
  hosts: dev-servers
  become: yes
  vars:
    namespace: test-production-deployment
    deployment_php_name: app-php-devops-deployment
    deployment_php_name: app-html-devops-deployment

  tasks:
    - name: Hacer rollback a la versión anterior
      ansible.builtin.command: >
        /snap/bin/microk8s kubectl rollout undo deployment/{{ deployment_php_name }}
        -n {{ namespace }}
      register: rollback_result

    - name: Mostrar resultado del rollback
      debug:
        var: rollback_result.stdout
