---
- name: Lanzar comandos de k8s
  hosts: dev-servers
  become: yes

  tasks:
    - name: Lanzar comandos de k8s
      shell: |
        /snap/bin/microk8s kubectl scale deployment app-{{ deploy_name }}-devops-deployment --replicas={{ replicas_number }}
      register: listar
      
    - name: Mostrar salida de listado
      debug:
        var: listar.stdout_lines