---
- name: Rollback del deployment a la versión anterior
  hosts: dev-servers
  become: yes
  vars:
    namespace: test-production-deployment
    deployment_html_name: app-php-devops-deployment
    deployment_php_name: app-html-devops-deployment

  tasks:
    - name: Hacer rollback a la versión anterior de html
      ansible.builtin.command: >
        /snap/bin/microk8s kubectl rollout undo deployment/{{ deployment_html_name }}
        -n {{ namespace }}
      register: rollback_result_html

    - name: Mostrar resultado del rollback de html
      debug:
        var: rollback_result_html.stdout

    - name: Hacer rollback a la versión anterior de php
      ansible.builtin.command: >
        /snap/bin/microk8s kubectl rollout undo deployment/{{ deployment_php_name }}
        -n {{ namespace }}
      register: rollback_result_php

    - name: Mostrar resultado del rollback de php
      debug:
        var: rollback_result_php.stdout
