---
- name: Lanzar comandos de k8s
  hosts: dev-servers
  become: yes
  vars:
    resource_k8s: all

  tasks:
    - name: Lanzar comandos de k8s
      shell: |
        /snap/bin/microk8s kubectl get {{ resource_k8s }}
      register: listar
      
    - name: Mostrar salida de listado
      debug:
        var: listar.stdout_lines