---
- name: Lanzar comandos de k8s
  hosts: dev-servers
  become: yes

  tasks:
    - name: Lanzar comandos de k8s
      shell: |
        cd /home/projects/k8s/app-html-devops/kubernetes
        /snap/bin/microk8s.kubectl apply -f app-project-devops-configmap-nginx.yaml
        /snap/bin/microk8s.kubectl rollout restart deployment/app-html-devops-deployment -n test-production-deployment
        /snap/bin/microk8s.kubectl rollout restart deployment/app-php-devops-deployment -n test-production-deployment

      register: listar
      
    - name: Mostrar salida de listado
      debug:
        var: listar.stdout_lines