---
- name: Lanzar comandos de k8s
  hosts: dev-servers
  become: yes

  tasks:
    - name: Lanzar comandos de k8s
      shell: |
        /snap/bin/microk8s kubectl apply -f kubernetes/app-project-devops-configmap-nginx.yaml
      register: listar
      
    - name: Mostrar salida de listado
      debug:
        var: listar.stdout_lines