apiVersion: v1
kind: Service
metadata:
  name: app-html-devops-service
spec:
  selector:
    app: app-html
    dep: devops
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer