apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: app-html-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-html-devops
  template:
    metadata:
      labels:
        app: app-html-devops
    spec:
      containers:
      - name: nginx
        image: rcastro95/app-html-devops:83fc7738420db0511751de1daea510ff8a930978
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1