name: Deploy HTML/NGINX

on:
  push:
    tags:
      - 'app-devops-html-v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Extract tag
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push NGINX image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: dockerfile_nginx
        push: true
        tags: |
          rcastro95/app-nginx-devops:${{ steps.tag.outputs.tag }}

    - name: Update NGINX deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCP_VM_IP_OR_HOSTNAME }}
        username: ${{ secrets.GCP_VM_USERNAME }}
        key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        port: ${{ secrets.GCP_VM_SSH_PORT || 22 }}
        script: |
          export PATH="$PATH:/snap/bin"
          cd /home/projects/k8s/app-html-devops
          git pull
          /snap/bin/microk8s kubectl config set-context --current --namespace=test-production-deployment
          microk8s.kubectl set image deployment/app-nginx-devops-deployment --namespace=test-production-deployment app-nginx-devops=rcastro95/app-nginx-devops:${{ steps.tag.outputs.tag }}

    - name: Notify Slack on success
      if: success()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": ":rocket: *¡HTML/NGINX desplegado con éxito!* :whale:\n\n*Tag:* `${{ steps.tag.outputs.tag }}`\n<${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ steps.tag.outputs.tag }}|🔗 Ver release>"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Slack on failure
      if: failure()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": ":x: *¡Fallo en despliegue de HTML/NGINX!* :boom:\n\n*Tag:* `${{ steps.tag.outputs.tag }}`\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|📋 Ver logs del workflow>"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
